// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase config for ToolMonitoring.
///
/// Replace placeholders after running `flutterfire configure`, or paste values
/// from Firebase Console → Project settings → Your apps.
class DefaultFirebaseOptions {
  static const String _placeholderMarker = 'REPLACE_WITH_FLUTTERFIRE';

  static bool get isConfigured {
    if (kIsWeb) {
      return !web.apiKey.contains(_placeholderMarker) &&
          !web.appId.contains(_placeholderMarker);
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return !android.apiKey.contains(_placeholderMarker);
      case TargetPlatform.iOS:
        return !ios.apiKey.contains(_placeholderMarker);
      case TargetPlatform.macOS:
        return !macos.apiKey.contains(_placeholderMarker) &&
            !macos.appId.contains('REPLACE_MACOS');
      case TargetPlatform.windows:
        return !windows.apiKey.contains(_placeholderMarker);
      default:
        return false;
    }
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Web app — Tool Monitoring Web (Firebase Console).
  /// Sinkronkan dengan `web/firebase-messaging-sw.js`.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxaQ80B3Au9KiMwk2m1lBLScMaEruSelI',
    appId: '1:264867704267:web:80e22ca914d552118a5a4e',
    messagingSenderId: '264867704267',
    projectId: 'toolmonitoring',
    authDomain: 'toolmonitoring.firebaseapp.com',
    storageBucket: 'toolmonitoring.firebasestorage.app',
    measurementId: 'G-7QLGSR3MV7',
  );

  /// Android package: `com.example.tool_store_app`
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsM7cS0PE0WKupDsu6SsQ_9M66l_0jeSM',
    appId: '1:264867704267:android:6735a652aba177b18a5a4e',
    messagingSenderId: '264867704267',
    projectId: 'toolmonitoring',
    storageBucket: 'toolmonitoring.firebasestorage.app',
  );

  /// iOS bundle id: `com.example.toolStoreApp`
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUWriWJ6m2Se2BZxZ7SbzDmpA4rTChnu8',
    appId: '1:264867704267:ios:249ec0cc8abba80d8a5a4e',
    messagingSenderId: '264867704267',
    projectId: 'toolmonitoring',
    storageBucket: 'toolmonitoring.firebasestorage.app',
    iosBundleId: 'com.example.toolStoreApp',
  );

  /// macOS bundle id: `com.example.toolStoreApp`
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUWriWJ6m2Se2BZxZ7SbzDmpA4rTChnu8',
    appId: '1:264867704267:ios:249ec0cc8abba80d8a5a4e',
    messagingSenderId: '264867704267',
    projectId: 'toolmonitoring',
    storageBucket: 'toolmonitoring.firebasestorage.app',
    iosBundleId: 'com.example.toolStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '$_placeholderMarker-WINDOWS-API-KEY',
    appId: '$_placeholderMarker-WINDOWS-APP-ID',
    messagingSenderId: '$_placeholderMarker-SENDER-ID',
    projectId: 'toolmonitoring',
    storageBucket: 'toolmonitoring.appspot.com',
  );
}
